version: '3.2'

services:

  apache:
    image: yiisoftware/yii2-php:8.1-apache
    ports:
      - 20080:80
      - 21080:8080
    volumes:
      # Re-use local composer cache via host-volume
      - ./apache/sites-enabled:/etc/apache2/sites-enabled
      - ./apache/ports.conf:/etc/apache2/ports.conf
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
    restart: unless-stopped
  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret